In [1]:
# ARRAY NUMPY

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns






In [3]:
 # LIST VSNUMPY ARRAY

In [4]:
List = [1,2,3]
print("list multiplication ",List*2)
print("numpy array multiplication ",np.array(List)*2)

list multiplication  [1, 2, 3, 1, 2, 3]
numpy array multiplication  [2 4 6]


In [5]:
# creating array from scratch

In [6]:
ones =np.ones((2,3))
print(ones)
sequence = np.arange(0,10,1)
print(sequence)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]


In [7]:
    # Vector -1D array ,Matrics -2 D arary  ,Tecsor - more than 2 D array

In [8]:
vactor = [1,2,3]
print(np.array(vactor),"\n")

matrix = [[1,2,3],[4,5,6]]
print(np.array(matrix),"\n")

tensor =[[[1,2],[4,5]],[[5,6],[7,9]]]
print(np.array(tensor))

[1 2 3] 

[[1 2 3]
 [4 5 6]] 

[[[1 2]
  [4 5]]

 [[5 6]
  [7 9]]]


In [9]:
# Array properties

In [10]:
arr = np.arange(12)
print(arr)

print(arr.shape)
print(arr.dtype)
print(arr.itemsize)
print(arr.size)

reshaped = arr.reshape((4,3))
print(reshaped)

# print(reshaped.shape)

# create a copy
flattend = arr.flatten()
print(flattend)


# change in original copy
raveld = arr.ravel()
print(raveld)

transposed = reshaped.T
print(transposed)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
int64
8
12
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [11]:
# Sorting arary

In [12]:
unsorted_1D =[1,8,-7,5,2,0,6]
print("sorted 1 D array ",np.sort(unsorted_1D))

unsorted_2D =[[1,3],[4,8],[7,-7]]
print("unsorted 2D array by columns \n",np.sort(unsorted_2D,axis=0))  #column wise all values sorted


print("unsorted 2D array  by rows\n",np.sort(unsorted_2D,axis=1)) # row wise all values sorted

sorted 1 D array  [-7  0  1  2  5  6  8]
unsorted 2D array by columns 
 [[ 1 -7]
 [ 4  3]
 [ 7  8]]
unsorted 2D array  by rows
 [[ 1  3]
 [ 4  8]
 [-7  7]]


In [13]:
    # Filters

In [14]:
numbers= np.arange(1,13)
print(numbers)
nums = numbers % 2==0
print(nums)

evens =numbers[numbers % 2==0]
print(evens)



[ 1  2  3  4  5  6  7  8  9 10 11 12]
[False  True False  True False  True False  True False  True False  True]
[ 2  4  6  8 10 12]


In [15]:
# Delete element

In [16]:
arr = [1,2,3,4,5,6,7,8,9,10]
deleted = np.delete(arr, 5)
print(deleted)

[ 1  2  3  4  5  7  8  9 10]


In [17]:
# RANDOM

In [18]:
any_num = np.random.rand()
print(any_num)

0.4477445307318978


In [19]:
any_num = np.random.rand(5,6)
print(any_num)

[[0.35608614 0.92908365 0.05339709 0.24782222 0.56994189 0.97039001]
 [0.76047848 0.3656381  0.88460249 0.57395032 0.71552433 0.06452093]
 [0.95525908 0.75962624 0.14124218 0.59441624 0.80842739 0.75829701]
 [0.22019464 0.53831212 0.07683259 0.44982595 0.47441767 0.86751902]
 [0.76317002 0.02856966 0.63332324 0.99573599 0.33409002 0.78336202]]


In [20]:
any_num = np.random.randint(100, size=(5,6))
print(any_num)

[[ 8 40 63 94 81 27]
 [79 87 37 56 57 95]
 [33 19 57 78 11 12]
 [62 27 76 72 93 81]
 [78 28 36 66 41 78]]


In [21]:
# arthmatic function

In [22]:
arr = np.array([1,2,3,4,5])
print(np.max(arr), np.argmax(arr1))
print(np.min(arr))
print(np.cos(arr))

NameError: name 'arr1' is not defined

In [ ]:
# cumulitive sum

In [ ]:
arr = np.array([1,2,3,4,5])
print(np.cumsum(arr))

In [ ]:
arr1= np.array([2,3,4,5])
print(arr1.shape)
print(arr1)
print()
arr2= np.array([[1],[2],[3],[4],[5]])
print(arr2.shape)
print(arr2)
print()
arr3= arr1+arr2
print(arr3)
print(arr3.shape)

In [ ]:
# join and split


In [ ]:
var =np.array([[1,2],[3,4]])
var2 = np.array([[1,8],[3,7]])
z=np.concatenate((var,var2),axis=0)
print(z)
print()
z1=np.concatenate((var,var2),axis=1)
print(z1)

In [ ]:
# matrix

In [ ]:
x = np.array([[1,2,3],[8,5,6]])
y=np.array([[1,2,3],[4,5,6]])



In [25]:
arr=[1,2,3]
arr

[1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 3]

In [27]:
data=[1,2,3,4,5]
arr=np.array(data)
arr

array([1, 2, 3, 4, 5])

In [28]:
arr.ndim

1

In [32]:
np.array([[[]]]).ndim

3

In [33]:
np.array([[[]]]).shape

(1, 1, 0)

In [40]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [38]:
data=[[1,2,3],[4,5,5]]
arr=np.array(data)
arr

array([[1, 2, 3],
       [4, 5, 5]])

In [41]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [42]:
np.full(10,12)

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [43]:
np.full([4,5],123)

array([[123, 123, 123, 123, 123],
       [123, 123, 123, 123, 123],
       [123, 123, 123, 123, 123],
       [123, 123, 123, 123, 123]])

In [44]:
np.empty([2,4])

array([[4.9e-324, 9.9e-324, 2.0e-323, 2.5e-323],
       [2.5e-323, 3.0e-323, 3.5e-323, 4.4e-323]])

In [46]:
np.random.rand(4)

array([0.36682064, 0.5668231 , 0.16187134, 0.86453935])

In [47]:
np.random.rand(4,4)

array([[0.54756163, 0.96301897, 0.90759701, 0.09679386],
       [0.65124431, 0.26794857, 0.17285638, 0.81795013],
       [0.76277254, 0.15780131, 0.74479368, 0.20576398],
       [0.59660001, 0.38932844, 0.72363986, 0.79906575]])

In [49]:
np.random.randint(10,size=6)

array([1, 3, 2, 5, 3, 0], dtype=int32)

In [50]:
da=np.random.rand(4,4)

In [51]:
da.size

16

In [52]:
da.itemsize

8

In [55]:
data=[1,2,3,4,5,6,7,8]
ar=np.array(data)

In [56]:
ard

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
_2dar=ar.reshape((3,2,1))

ValueError: cannot reshape array of size 8 into shape (3,2,1)

In [67]:
_2dar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
_2dar.ravel()  # 1D array only view

array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
_2dar.flatten() # 1D array copy

array([1, 2, 3, 4, 5, 6, 7, 8])

In [71]:
np.array([[[1,2,3],[4,5,6]],[[9,7,8],[7,5,4]]]).flatten()

array([1, 2, 3, 4, 5, 6, 9, 7, 8, 7, 5, 4])

In [72]:
data=[[1,2,3],[4,5,6],[7,8,10]]
arr=np.array(data)

In [73]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [75]:
arr[:,1:]     

array([[ 2,  3],
       [ 5,  6],
       [ 8, 10]])

In [76]:
arr[1:2,:]

array([[4, 5, 6]])

In [77]:
arr[1:,1:]

array([[ 5,  6],
       [ 8, 10]])

In [78]:
for index ,i in np.ndenumerate(arr):
    print(index,i)
    

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 10


In [80]:
arr.transpose()

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6, 10]])

In [85]:
a=np.array(['a','b','e'])
b=np.array(['c','d','f'])
c=np.concatenate((a,b))



In [86]:
c

array(['a', 'b', 'e', 'c', 'd', 'f'], dtype='<U1')

In [87]:
v=np.vstack((a,b))
v

array([['a', 'b', 'e'],
       ['c', 'd', 'f']], dtype='<U1')

In [88]:
a=[['a','b'],['c','d']]
a=np.array(a)
b=[['e','f'],['g','h']]
b=np.array(b)

In [91]:
d=np.concatenate((a,b),axis=1)

In [92]:
d

array([['a', 'b', 'e', 'f'],
       ['c', 'd', 'g', 'h']], dtype='<U1')

In [93]:
data=[1,2,3,4,5,6,8,9,10]
arr=np.array(data)
arr

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10])

In [99]:
result=np.where(arr%2==0,"even","odd")

In [100]:
result

array(['odd', 'even', 'odd', 'even', 'odd', 'even', 'even', 'odd', 'even'],
      dtype='<U4')

In [106]:
#VECTORIZED
# np.vectorize--->convert a normal function to be apply np array

In [107]:
def square(x):
    return x*x

arr=np.array([1,2,3,4,5])
vectorfunc=np.vectorize(square)


In [104]:
vectorfunc(arr)

array([ 1,  4,  9, 16, 25])