In [ ]:
# ARRAY NUMPY

In [2]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)



[1 2 3 4 5]


In [ ]:
 # LIST VSNUMPY ARRAY

In [3]:
List = [1,2,3]
print("list multiplication ",List*2)
print("numpy array multiplication ",np.array(List)*2)

list multiplication  [1, 2, 3, 1, 2, 3]
numpy array multiplication  [2 4 6]


In [ ]:
# creating array from scratch

In [6]:
ones =np.ones((2,3))
print(ones)
sequence = np.arange(0,10,1)
print(sequence)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
    # Vector -1D array ,Matrics -2 D arary  ,Tecsor - more than 2 D array

In [8]:
vactor = [1,2,3]
print(np.array(vactor),"\n")

matrix = [[1,2,3],[4,5,6]]
print(np.array(matrix),"\n")

tensor =[[[1,2],[4,5]],[[5,6],[7,9]]]
print(np.array(tensor))

[1 2 3] 

[[1 2 3]
 [4 5 6]] 

[[[1 2]
  [4 5]]

 [[5 6]
  [7 9]]]


In [ ]:
# Array properties

In [24]:
arr = np.arange(12)
print(arr)

print(arr.shape)
print(arr.dtype)
print(arr.itemsize)
print(arr.size)

reshaped = arr.reshape((4,3))
print(reshaped)

# print(reshaped.shape)

# create a copy
flattend = arr.flatten()
print(flattend)


# change in original copy
raveld = arr.ravel()
print(raveld)

transposed = reshaped.T
print(transposed)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
int64
8
12
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [ ]:
# Sorting arary

In [25]:
unsorted_1D =[1,8,-7,5,2,0,6]
print("sorted 1 D array ",np.sort(unsorted_1D))

unsorted_2D =[[1,3],[4,8],[7,-7]]
print("unsorted 2D array by columns \n",np.sort(unsorted_2D,axis=0))  #column wise all values sorted


print("unsorted 2D array  by rows\n",np.sort(unsorted_2D,axis=1)) # row wise all values sorted

sorted 1 D array  [-7  0  1  2  5  6  8]
unsorted 2D array by columns 
 [[ 1 -7]
 [ 4  3]
 [ 7  8]]
unsorted 2D array  by rows
 [[ 1  3]
 [ 4  8]
 [-7  7]]


In [ ]:
    # Filters

In [28]:
numbers= np.arange(1,13)
print(numbers)
nums = numbers % 2==0
print(nums)

evens =numbers[numbers % 2==0]
print(evens)



[ 1  2  3  4  5  6  7  8  9 10 11 12]
[False  True False  True False  True False  True False  True False  True]
[ 2  4  6  8 10 12]
