In [26]:
# ARRAY NUMPY

In [27]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns






In [28]:
 # LIST VSNUMPY ARRAY

In [29]:
List = [1,2,3]
print("list multiplication ",List*2)
print("numpy array multiplication ",np.array(List)*2)

list multiplication  [1, 2, 3, 1, 2, 3]
numpy array multiplication  [2 4 6]


In [30]:
# creating array from scratch

In [31]:
ones =np.ones((2,3))
print(ones)
sequence = np.arange(0,10,1)
print(sequence)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2 3 4 5 6 7 8 9]


In [32]:
    # Vector -1D array ,Matrics -2 D arary  ,Tecsor - more than 2 D array

In [33]:
vactor = [1,2,3]
print(np.array(vactor),"\n")

matrix = [[1,2,3],[4,5,6]]
print(np.array(matrix),"\n")

tensor =[[[1,2],[4,5]],[[5,6],[7,9]]]
print(np.array(tensor))

[1 2 3] 

[[1 2 3]
 [4 5 6]] 

[[[1 2]
  [4 5]]

 [[5 6]
  [7 9]]]


In [34]:
# Array properties

In [35]:
arr = np.arange(12)
print(arr)

print(arr.shape)
print(arr.dtype)
print(arr.itemsize)
print(arr.size)

reshaped = arr.reshape((4,3))
print(reshaped)

# print(reshaped.shape)

# create a copy
flattend = arr.flatten()
print(flattend)


# change in original copy
raveld = arr.ravel()
print(raveld)

transposed = reshaped.T
print(transposed)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
int64
8
12
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [36]:
# Sorting arary

In [37]:
unsorted_1D =[1,8,-7,5,2,0,6]
print("sorted 1 D array ",np.sort(unsorted_1D))

unsorted_2D =[[1,3],[4,8],[7,-7]]
print("unsorted 2D array by columns \n",np.sort(unsorted_2D,axis=0))  #column wise all values sorted


print("unsorted 2D array  by rows\n",np.sort(unsorted_2D,axis=1)) # row wise all values sorted

sorted 1 D array  [-7  0  1  2  5  6  8]
unsorted 2D array by columns 
 [[ 1 -7]
 [ 4  3]
 [ 7  8]]
unsorted 2D array  by rows
 [[ 1  3]
 [ 4  8]
 [-7  7]]


In [38]:
    # Filters

In [39]:
numbers= np.arange(1,13)
print(numbers)
nums = numbers % 2==0
print(nums)

evens =numbers[numbers % 2==0]
print(evens)



[ 1  2  3  4  5  6  7  8  9 10 11 12]
[False  True False  True False  True False  True False  True False  True]
[ 2  4  6  8 10 12]


In [40]:
# Delete element

In [41]:
arr = [1,2,3,4,5,6,7,8,9,10]
deleted = np.delete(arr, 5)
print(deleted)

[ 1  2  3  4  5  7  8  9 10]


In [42]:
# RANDOM

In [43]:
any_num = np.random.rand()
print(any_num)

0.5343800530568976


In [44]:
any_num = np.random.rand(5,6)
print(any_num)

[[0.0363963  0.25256892 0.66462776 0.17747577 0.3284421  0.99705157]
 [0.18818185 0.32223322 0.32853347 0.56024754 0.25408558 0.27352456]
 [0.10396475 0.48058994 0.39225661 0.93614723 0.20072788 0.31499565]
 [0.07926375 0.09355502 0.28486193 0.38693537 0.2589254  0.58678859]
 [0.56728073 0.26880666 0.89635466 0.27322899 0.43454548 0.75639037]]


In [45]:
any_num = np.random.randint(100, size=(5,6))
print(any_num)

[[29 77 57 44 10 98]
 [21 64 36 84 35 41]
 [69 42 51 25 65 81]
 [70 64  8 64 33 52]
 [35 75 75 65 51 46]]


In [46]:
# arthmatic function

In [47]:
arr = np.array([1,2,3,4,5])
print(np.max(arr), np.argmax(arr1))
print(np.min(arr))
print(np.cos(arr))

NameError: name 'arr1' is not defined

In [ ]:
# cumulitive sum

In [ ]:
arr = np.array([1,2,3,4,5])
print(np.cumsum(arr))

In [48]:
arr1= np.array([2,3,4,5])
print(arr1.shape)
print(arr1)
print()
arr2= np.array([[1],[2],[3],[4],[5]])
print(arr2.shape)
print(arr2)
print()
arr3= arr1+arr2
print(arr3)
print(arr3.shape)

(4,)
[2 3 4 5]

(5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]

[[ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]
(5, 4)


In [49]:
# join and split


In [50]:
var =np.array([[1,2],[3,4]])
var2 = np.array([[1,8],[3,7]])
z=np.concatenate((var,var2),axis=0)
print(z)
print()
z1=np.concatenate((var,var2),axis=1)
print(z1)

[[1 2]
 [3 4]
 [1 8]
 [3 7]]

[[1 2 1 8]
 [3 4 3 7]]


In [51]:
# matrix

In [52]:
x = np.array([[1,2,3],[8,5,6]])
y=np.array([[1,2,3],[4,5,6]])



In [53]:
arr=[1,2,3]
arr

[1, 2, 3]

In [54]:
data=[1,2,3,4,5]
arr=np.array(data)
arr

array([1, 2, 3, 4, 5])

In [55]:
arr.ndim

1

In [56]:
np.array([[[]]]).ndim

3

In [57]:
np.array([[[]]]).shape

(1, 1, 0)

In [58]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
data=[[1,2,3],[4,5,5]]
arr=np.array(data)
arr

array([[1, 2, 3],
       [4, 5, 5]])

In [61]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [62]:
np.full(10,12)

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [63]:
np.full([4,5],123)

array([[123, 123, 123, 123, 123],
       [123, 123, 123, 123, 123],
       [123, 123, 123, 123, 123],
       [123, 123, 123, 123, 123]])

In [64]:
np.empty([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
np.random.rand(4)

array([0.83261665, 0.54180173, 0.50989905, 0.5239975 ])

In [66]:
np.random.rand(4,4)

array([[0.85183631, 0.28161232, 0.9044399 , 0.69411085],
       [0.2819372 , 0.55835848, 0.54613889, 0.76498441],
       [0.44558613, 0.90738181, 0.12588478, 0.55235186],
       [0.29899565, 0.02873116, 0.81413983, 0.74110548]])

In [67]:
np.random.randint(10,size=6)

array([9, 1, 9, 0, 0, 9], dtype=int32)

In [68]:
da=np.random.rand(4,4)

In [69]:
da.size

16

In [70]:
da.itemsize

8

In [71]:
data=[1,2,3,4,5,6,7,8]
ar=np.array(data)

In [72]:
ard

NameError: name 'ard' is not defined

In [73]:
_2dar=ar.reshape((3,2,1))

ValueError: cannot reshape array of size 8 into shape (3,2,1)

In [74]:
_2dar

NameError: name '_2dar' is not defined

In [75]:
_2dar.ravel()  # 1D array only view

NameError: name '_2dar' is not defined

In [76]:
_2dar.flatten() # 1D array copy

NameError: name '_2dar' is not defined

In [77]:
np.array([[[1,2,3],[4,5,6]],[[9,7,8],[7,5,4]]]).flatten()

array([1, 2, 3, 4, 5, 6, 9, 7, 8, 7, 5, 4])

In [78]:
data=[[1,2,3],[4,5,6],[7,8,10]]
arr=np.array(data)

In [79]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [80]:
arr[:,1:]     

array([[ 2,  3],
       [ 5,  6],
       [ 8, 10]])

In [81]:
arr[1:2,:]

array([[4, 5, 6]])

In [82]:
arr[1:,1:]

array([[ 5,  6],
       [ 8, 10]])

In [83]:
for index ,i in np.ndenumerate(arr):
    print(index,i)
    

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 10


In [84]:
arr.transpose()

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6, 10]])

In [105]:
arr=np.array([[1,2],[8,5]])

In [106]:
np.linalg.det(arr)

np.float64(-10.999999999999996)

In [104]:
a=np.array(['a','b','e'])
b=np.array(['c','d','f'])
c=np.concatenate((a,b))



In [86]:
c

array(['a', 'b', 'e', 'c', 'd', 'f'], dtype='<U1')

In [87]:
v=np.vstack((a,b))
v

array([['a', 'b', 'e'],
       ['c', 'd', 'f']], dtype='<U1')

In [88]:
a=[['a','b'],['c','d']]
a=np.array(a)
b=[['e','f'],['g','h']]
b=np.array(b)

In [89]:
d=np.concatenate((a,b),axis=1)

In [90]:
d

array([['a', 'b', 'e', 'f'],
       ['c', 'd', 'g', 'h']], dtype='<U1')

In [91]:
data=[1,2,3,4,5,6,8,9,10]
arr=np.array(data)
arr

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10])

In [92]:
result=np.where(arr%2==0,"even","odd")

In [93]:
result

array(['odd', 'even', 'odd', 'even', 'odd', 'even', 'even', 'odd', 'even'],
      dtype='<U4')

In [94]:
#VECTORIZED
# np.vectorize--->convert a normal function to be apply np array

In [95]:
def square(x):
    return x*x

arr=np.array([1,2,3,4,5])
vectorfunc=np.vectorize(square)


In [96]:
vectorfunc(arr)

array([ 1,  4,  9, 16, 25])

In [97]:
stu={'id':[123,124,125,126,127],
     'name':['Alice','Bob','Carol','joy','josh'],
     'age':[21,22,23,24,20]
     }
stu=(stu)
stu

{'id': [123, 124, 125, 126, 127],
 'name': ['Alice', 'Bob', 'Carol', 'joy', 'josh'],
 'age': [21, 22, 23, 24, 20]}

In [1]:
even_numbers = [num for num in [1, 2, 3, 4, 5, 6] if num % 2 == 0 ]
# Result: [2, 4, 6]
